/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverlayDockManagerRouteImport } from './routes/overlay/dock-manager'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayDockManagerRoute = OverlayDockManagerRouteImport.update({
  id: '/overlay/dock-manager',
  path: '/overlay/dock-manager',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overlay/dock-manager': typeof OverlayDockManagerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overlay/dock-manager': typeof OverlayDockManagerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overlay/dock-manager': typeof OverlayDockManagerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/overlay/dock-manager'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/overlay/dock-manager'
  id: '__root__' | '/' | '/overlay/dock-manager'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverlayDockManagerRoute: typeof OverlayDockManagerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/dock-manager': {
      id: '/overlay/dock-manager'
      path: '/overlay/dock-manager'
      fullPath: '/overlay/dock-manager'
      preLoaderRoute: typeof OverlayDockManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverlayDockManagerRoute: OverlayDockManagerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
